---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster
  namespace: vm-operator
spec:
  retentionPeriod: "1"
  vmstorage:
    replicaCount: 1
  vminsert:
    replicaCount: 1
  vmselect:
    replicaCount: 1
