---
- name: Install MetalLB via Helm
  hosts: control
  become: false
  vars:
    metallb_ip: 192.168.178.201

  tasks:

    - name: Check if Helm is installed
      command: which helm
      register: helm_installed
      ignore_errors: true
      changed_when: false

    - name: Install Helm binary if missing
      become: true
      shell: |
        curl -s https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        executable: /bin/bash
      when: helm_installed.rc != 0

    - name: Ensure metallb-system namespace exists
      shell: |
        kubectl get namespace metallb-system || kubectl create namespace metallb-system
      changed_when: "'created' in result.stdout"
      register: result


    - name: Add Helm repo for MetalLB
      command: helm repo add metallb https://metallb.github.io/metallb
      args:
        creates: ~/.cache/helm/repository/metallb-index.yaml

    - name: Update Helm repos
      command: helm repo update
      changed_when: false

    - name: Install or upgrade MetalLB
      command: >
        helm upgrade --install metallb metallb/metallb
        --namespace metallb-system
      args:
        creates: /etc/rancher/k3s/metallb-installed-marker

    - name: Copy MetalLB config YAML to control node
      copy:
        src: metallb-rancher-pool.yaml
        dest: /tmp/metallb-rancher-pool.yaml

    - name: Wait for MetalLB controller to be ready
      shell: |
        kubectl wait --namespace metallb-system \
          --for=condition=Ready pod \
          --selector=app.kubernetes.io/component=controller \
          --timeout=60s
      register: wait_result

    - name: Check if MetalLB IPAddressPool exists
      shell: |
        kubectl get ipaddresspool -n metallb-system services-pool --no-headers
      register: ip_pool_check
      failed_when: false
      changed_when: false

    - name: Apply MetalLB config if IPAddressPool doesn't exist
      command: kubectl apply -f /tmp/metallb-rancher-pool.yaml
      when: ip_pool_check.rc != 0
