---
- name: Install Rancher via Helm using Traefik ingress
  hosts: control
  become: false
  vars:
    rancher_hostname: rancher.lab.local
  tasks:

    - name: Create cattle-system namespace
      command: kubectl create namespace cattle-system
      register: ns_create
      failed_when: false
      changed_when: "'created' in ns_create.stdout"

    - name: Add Rancher Helm repo
      command: helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
      changed_when: true

    - name: Update Helm repos
      command: helm repo update
      changed_when: true

    - name: Install cert-manager CRDs (required for Rancher)
      command: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/latest/download/cert-manager.crds.yaml
      changed_when: true

    - name: Add Jetstack Helm repo for cert-manager
      command: helm repo add jetstack https://charts.jetstack.io
      changed_when: true


    - name: Install cert-manager via Helm
      command: >
        helm upgrade --install cert-manager jetstack/cert-manager
        --namespace cert-manager
        --create-namespace
        --version v1.14.2
      changed_when: true

    - name: Install Rancher (Ingress via Traefik)
      command: >
        helm upgrade --install rancher rancher-latest/rancher
        --namespace cattle-system
        --set hostname={{ rancher_hostname }}
        --set ingress.tls.source=letsEncrypt
        --set ingress.ingressClassName=traefik
        --set ingress.annotations."cert-manager\.io/issuer"=-
        --set ingress.annotations."cert-manager\.io/issuer-kind"=-
        --set replicas=1
      changed_when: true

    - name: Wait for Rancher deployment to be ready
      shell: |
        kubectl -n cattle-system rollout status deploy/rancher --timeout=120s
      register: rollout_status
      changed_when: false

    - name: Wait for Rancher bootstrap secret to exist
      shell: kubectl -n cattle-system get secret bootstrap-secret
      register: rancher_secret_check
      retries: 10
      delay: 5
      until: rancher_secret_check.rc == 0
      changed_when: false

    - name: Get Rancher bootstrap password
      command: >
        kubectl -n cattle-system get secret bootstrap-secret
        -o go-template='{{ "{{ .data.bootstrapPassword | base64decode }}" }}'
      register: rancher_bootstrap

    - name: Show Rancher URL
      debug:
        msg: "🚀 Rancher is deployed! ➤ URL: https://{{ rancher_hostname }}"

    - name: Show Rancher bootstrap password
      debug:
        msg: "🔑 Bootstrap password: {{ rancher_bootstrap.stdout }}"
