---
- name: Install VictoriaMetrics Operator and monitoring stack
  hosts: control
  become: false
  tasks:

    - name: Create VM operator namespace
      command: kubectl create namespace vm-operator
      register: ns_create
      failed_when: false
      changed_when: "'created' in ns_create.stdout"

    - name: Add VictoriaMetrics Helm repo
      command: helm repo add vm https://victoriametrics.github.io/helm-charts/
      changed_when: true

    - name: Update Helm repos
      command: helm repo update
      changed_when: true

    - name: Install VictoriaMetrics Operator via Helm
      command: >
        helm upgrade --install vm-operator vm/victoria-metrics-operator
        --namespace vm-operator
        --create-namespace
      changed_when: true

    - name: Wait for VictoriaMetrics operator to become ready
      shell: |
        kubectl rollout status deployment/vm-operator-victoria-metrics-operator \
          -n vm-operator --timeout=60s
      changed_when: false

    - name: Copy victoriametrics_cluster.yaml file over
      copy:
        src: victoriametrics_cluster.yaml
        dest: /tmp/victoriametrics_cluster.yaml

    - name: Apply VMCluster manifest
      command: kubectl apply -f /tmp/victoriametrics_cluster.yaml

    - name: Copy victoriametrics_agent.yaml file over
      copy:
        src: victoriametrics_agent.yaml
        dest: /tmp/victoriametrics_agent.yaml

    - name: Apply VMAgent manifest
      command: kubectl apply -f /tmp/victoriametrics_agent.yaml

    - name: Add VM Metrics to use Ingress
      copy:
        dest: /tmp/vm-metrics-lb.yaml
        content: |
          apiVersion: v1
          kind: Service
          metadata:
            name: vm-metrics
            namespace: vm-operator
          spec:
            type: ClusterIP
            ports:
              - name: http
                port: 80
                targetPort: 8481
            selector:
              app.kubernetes.io/name: vmselect

    - name: Copy victoriametrics_agent.yaml file over
      copy:
        src: node-exporter.yaml
        dest: /tmp/node-exporter.yaml

    - name: Apply  service for metrics UI
      command: kubectl apply -f /tmp/vm-metrics-lb.yaml


    - name: Apply node-exporter DaemonSet
      command: kubectl apply -f /tmp/node-exporter.yaml

    - name: Copy vmscrape-nodeexporter.yaml file over
      copy:
        src: vmscrape-nodeexporter.yaml
        dest: /tmp/vmscrape-nodeexporter.yaml

    - name: Apply VMServiceScrape for node-exporter
      command: kubectl apply -f /tmp/vmscrape-nodeexporter.yaml

    - name: Copy vmscrape-nodeexporter.yaml file over
      copy:
        src: node-exporter-svc.yaml
        dest: /tmp/node-exporter-svc.yaml

    - name: Apply Service for node-exporter
      command: kubectl apply -f /tmp/node-exporter-svc.yaml

    - name: Show VictoriaMetrics message
      debug:
        msg: |
          VictoriaMetrics is exposed!

    - name: Show VictoriaMetrics external URL
      debug:
        msg: |
          ➤ Visit: http://metrics.lab.local

